main: com.vincentvansetten.vessentials.VEssentials
name: VEssentials
version: ' 0.2'
author: Vincent Vvamp van Setten
description: All-In-One plugin for the 'New Beginnings' server
commands:
  vessentials:
    default: true
    description: Shows a list of commands
    usage: /vessentials [help] 
    aliases:
      - ve
    permission: vessentials.vessentials 
    permission-message: You don't have the permission to use vessentials!
  hug:
    default: true
    description: Hug a player
    usage: /hug <player>
    permission: vessentials.hug
    permission-message: You don't have the permission to use hug!
  kiss:
    default: true
    description: Kiss a player
    usage: /kiss <player>
    permission: vessentials.kiss
    permission-message: You don't have the permission to use kiss!
  fakeleave:
    default: op
    description: Sends a fake 'leave' message 
    usage: /fakeleave
    permission: vessentials.fakeleave 
    permission-message: You don't have the permission to use Fake Leave!
  fakejoin:
    default: op
    description: Sends a fake 'join' message 
    usage: /fakejoin
    permission: vessentials.fakejoin
    permission-message: You don't have the permission to use Fake Join!
  vanish:
    default: op
    description: Toggles vanish on a player
    usage: /vanish 
    permission: vessentials.vanish
    permission-message: You don't have the permission to use Vanish!
    aliases:
      - v
  warning:
    default: op
    description: Issues a warning to a player
    usage: /warning <reason>
    permission: vessentials.warning
    permission-message: You don't have the permission to issue warnings to other players!
    aliases:
      - warn
     